version: "3.1"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: project
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
    ports:
      - 27001:27017
    volumes:
      - dbdata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - ${VCAP_APP_PORT}:${VCAP_APP_PORT}
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      VCAP_APP_HOST: ${VCAP_APP_HOST}
      VCAP_APP_PORT: ${VCAP_APP_PORT}
volumes:
  dbdata: